//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 11:03:48 AM CEST 
//


package org.netarchivesuite.fitswrapper.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statisticsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statisticsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tool" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://hul.harvard.edu/ois/xml/ns/fits/fits_output}nameVersionAttrGrp"/>
 *                 &lt;attribute name="executionTime" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="fitsExecutionTime" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statisticsType", propOrder = {
    "tool"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class StatisticsType {

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<StatisticsType.Tool> tool;
    @XmlAttribute(name = "fitsExecutionTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger fitsExecutionTime;

    /**
     * Gets the value of the tool property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tool property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTool().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatisticsType.Tool }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<StatisticsType.Tool> getTool() {
        if (tool == null) {
            tool = new ArrayList<StatisticsType.Tool>();
        }
        return this.tool;
    }

    /**
     * Gets the value of the fitsExecutionTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getFitsExecutionTime() {
        return fitsExecutionTime;
    }

    /**
     * Sets the value of the fitsExecutionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setFitsExecutionTime(BigInteger value) {
        this.fitsExecutionTime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://hul.harvard.edu/ois/xml/ns/fits/fits_output}nameVersionAttrGrp"/>
     *       &lt;attribute name="executionTime" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Tool {

        @XmlAttribute(name = "executionTime")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected BigInteger executionTime;
        @XmlAttribute(name = "status")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String status;
        @XmlAttribute(name = "toolname")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String toolname;
        @XmlAttribute(name = "toolversion")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String toolversion;

        /**
         * Gets the value of the executionTime property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public BigInteger getExecutionTime() {
            return executionTime;
        }

        /**
         * Sets the value of the executionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setExecutionTime(BigInteger value) {
            this.executionTime = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the toolname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getToolname() {
            return toolname;
        }

        /**
         * Sets the value of the toolname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setToolname(String value) {
            this.toolname = value;
        }

        /**
         * Gets the value of the toolversion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getToolversion() {
            return toolversion;
        }

        /**
         * Sets the value of the toolversion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2015-10-08T11:03:48+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setToolversion(String value) {
            this.toolversion = value;
        }

    }

}
